/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aop_group_prjct;

import static java.lang.Character.digit;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFormattedTextField.AbstractFormatter;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author olegk
 */
public class GUI_terminal extends javax.swing.JFrame {

    ConnectDB DataBaseObject = new ConnectDB();
    TerminalButtons TB = new TerminalButtons();
    User currentUser = null;

    /**
     * Creates new form GUI_terminal
     */
    public GUI_terminal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CardPanel = new javax.swing.JPanel();
        cBankLabel = new javax.swing.JLabel();
        InsertLabel = new javax.swing.JLabel();
        SignInLabel = new javax.swing.JLabel();
        CardField = new javax.swing.JFormattedTextField();
        cButton1 = new javax.swing.JButton();
        cButton2 = new javax.swing.JButton();
        cButton3 = new javax.swing.JButton();
        cButton4 = new javax.swing.JButton();
        cButton5 = new javax.swing.JButton();
        cButton6 = new javax.swing.JButton();
        cButton7 = new javax.swing.JButton();
        cButton8 = new javax.swing.JButton();
        cButton9 = new javax.swing.JButton();
        cButtonDel = new javax.swing.JButton();
        cButton0 = new javax.swing.JButton();
        cButtonNext = new javax.swing.JButton();
        CardLabel = new javax.swing.JLabel();
        PinPanel = new javax.swing.JPanel();
        WrongPinFrame = new javax.swing.JInternalFrame();
        wpLabel1 = new javax.swing.JLabel();
        wpLabel2 = new javax.swing.JLabel();
        wpButton1 = new javax.swing.JButton();
        wpButton2 = new javax.swing.JButton();
        pBankLabel = new javax.swing.JLabel();
        pEnterLabel = new javax.swing.JLabel();
        pButton1 = new javax.swing.JButton();
        pButton2 = new javax.swing.JButton();
        pButton3 = new javax.swing.JButton();
        pButton4 = new javax.swing.JButton();
        pButton5 = new javax.swing.JButton();
        pButton6 = new javax.swing.JButton();
        pButton7 = new javax.swing.JButton();
        pButton8 = new javax.swing.JButton();
        pButton9 = new javax.swing.JButton();
        pButton0 = new javax.swing.JButton();
        pButtonDel = new javax.swing.JButton();
        pButtonNext = new javax.swing.JButton();
        pPasswordField = new javax.swing.JPasswordField();
        StartPanel = new javax.swing.JPanel();
        sBankLabel = new javax.swing.JLabel();
        sLabel1 = new javax.swing.JLabel();
        sLabel2 = new javax.swing.JLabel();
        sDatalabelPanel = new javax.swing.JLabel();
        sLabel3 = new javax.swing.JLabel();
        sSeparator = new javax.swing.JSeparator();
        sInsertLabel = new javax.swing.JLabel();
        sPhoneLabel = new javax.swing.JLabel();
        sPhoneField = new javax.swing.JFormattedTextField();
        sLabel4 = new javax.swing.JLabel();
        sLabel5 = new javax.swing.JLabel();
        sButton1 = new javax.swing.JButton();
        sButton2 = new javax.swing.JButton();
        sButton3 = new javax.swing.JButton();
        sButton4 = new javax.swing.JButton();
        sButton5 = new javax.swing.JButton();
        sButton6 = new javax.swing.JButton();
        sButton7 = new javax.swing.JButton();
        sButton8 = new javax.swing.JButton();
        sButton9 = new javax.swing.JButton();
        sButton0 = new javax.swing.JButton();
        sButtonDel = new javax.swing.JButton();
        sButtonNext = new javax.swing.JButton();
        PanelUserMenu = new javax.swing.JPanel();
        PanelMenuLogo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        PanelMenuTitle = new javax.swing.JLabel();
        PanelMenuTopUp = new javax.swing.JLabel();
        PanelMenuReplenish = new javax.swing.JLabel();
        PanelMenuContacts = new javax.swing.JLabel();
        PanelMenuBalance = new javax.swing.JLabel();
        PanelMenuTransfer = new javax.swing.JLabel();
        PanelMenuExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CardPanel.setBackground(new java.awt.Color(0, 100, 39));

        cBankLabel.setBackground(new java.awt.Color(0, 0, 0));
        cBankLabel.setFont(new java.awt.Font("Marcellus SC", 1, 36)); // NOI18N
        cBankLabel.setForeground(new java.awt.Color(255, 255, 255));
        cBankLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconPrivate.png"))); // NOI18N
        cBankLabel.setText("UnprivateBank");

        InsertLabel.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        InsertLabel.setForeground(new java.awt.Color(255, 255, 255));
        InsertLabel.setText("Insert the card");

        SignInLabel.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        SignInLabel.setForeground(new java.awt.Color(255, 255, 255));
        SignInLabel.setText("Sign In");
        SignInLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        CardField.setBackground(new java.awt.Color(0, 161, 33));
        CardField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        CardField.setForeground(new java.awt.Color(255, 255, 255));
        try {
            CardField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CardField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CardField.setToolTipText("");
        CardField.setFont(new java.awt.Font("Marcellus SC", 1, 14)); // NOI18N
        CardField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardFieldActionPerformed(evt);
            }
        });

        cButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        cButton1.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        cButton1.setText("1");
        cButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButton1ActionPerformed(evt);
            }
        });

        cButton2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        cButton2.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        cButton2.setText("2");
        cButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButton2ActionPerformed(evt);
            }
        });

        cButton3.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        cButton3.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        cButton3.setText("3");
        cButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButton3ActionPerformed(evt);
            }
        });

        cButton4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        cButton4.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        cButton4.setText("4");
        cButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButton4ActionPerformed(evt);
            }
        });

        cButton5.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        cButton5.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        cButton5.setText("5");
        cButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButton5ActionPerformed(evt);
            }
        });

        cButton6.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        cButton6.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        cButton6.setText("6");
        cButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButton6ActionPerformed(evt);
            }
        });

        cButton7.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        cButton7.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        cButton7.setText("7");
        cButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButton7ActionPerformed(evt);
            }
        });

        cButton8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        cButton8.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        cButton8.setText("8");
        cButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButton8ActionPerformed(evt);
            }
        });

        cButton9.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        cButton9.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        cButton9.setText("9");
        cButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButton9ActionPerformed(evt);
            }
        });

        cButtonDel.setBackground(new java.awt.Color(204, 0, 0));
        cButtonDel.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        cButtonDel.setText("X");
        cButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonDelActionPerformed(evt);
            }
        });

        cButton0.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        cButton0.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        cButton0.setText("0");
        cButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButton0ActionPerformed(evt);
            }
        });

        cButtonNext.setBackground(new java.awt.Color(51, 204, 0));
        cButtonNext.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        cButtonNext.setText("Next");
        cButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonNextActionPerformed(evt);
            }
        });

        CardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconInsertCard.png"))); // NOI18N

        javax.swing.GroupLayout CardPanelLayout = new javax.swing.GroupLayout(CardPanel);
        CardPanel.setLayout(CardPanelLayout);
        CardPanelLayout.setHorizontalGroup(
            CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardPanelLayout.createSequentialGroup()
                .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cBankLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CardPanelLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(SignInLabel))
                    .addGroup(CardPanelLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(CardLabel)
                        .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CardPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CardPanelLayout.createSequentialGroup()
                                        .addComponent(cButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(CardPanelLayout.createSequentialGroup()
                                        .addComponent(cButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(CardPanelLayout.createSequentialGroup()
                                        .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(CardPanelLayout.createSequentialGroup()
                                                .addComponent(cButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(CardPanelLayout.createSequentialGroup()
                                                .addComponent(cButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(CardField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CardPanelLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(InsertLabel)))))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        CardPanelLayout.setVerticalGroup(
            CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cBankLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignInLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardPanelLayout.createSequentialGroup()
                        .addComponent(InsertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CardField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(CardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        CardPanel.setVisible(false);

        PinPanel.setBackground(new java.awt.Color(51, 102, 0));
        PinPanel.setVisible(false);
        PinPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WrongPinFrame.setBackground(new java.awt.Color(204, 204, 204));
        WrongPinFrame.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        WrongPinFrame.setForeground(new java.awt.Color(255, 255, 255));
        WrongPinFrame.setTitle("UnprivateBank Message");
        WrongPinFrame.setVisible(false);

        wpLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconWrongPincode.png"))); // NOI18N

        wpLabel2.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        wpLabel2.setText("Wrong Pincode");

        wpButton1.setBackground(new java.awt.Color(204, 204, 204));
        wpButton1.setFont(new java.awt.Font("Marcellus SC", 1, 12)); // NOI18N
        wpButton1.setText("Go to Log-In");
        wpButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wpButton1ActionPerformed(evt);
            }
        });

        wpButton2.setBackground(new java.awt.Color(204, 204, 204));
        wpButton2.setFont(new java.awt.Font("Marcellus SC", 1, 12)); // NOI18N
        wpButton2.setText("Try one more");
        wpButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wpButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WrongPinFrameLayout = new javax.swing.GroupLayout(WrongPinFrame.getContentPane());
        WrongPinFrame.getContentPane().setLayout(WrongPinFrameLayout);
        WrongPinFrameLayout.setHorizontalGroup(
            WrongPinFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WrongPinFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wpButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wpLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(wpButton2)
                .addContainerGap())
            .addGroup(WrongPinFrameLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(wpLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        WrongPinFrameLayout.setVerticalGroup(
            WrongPinFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WrongPinFrameLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(wpLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WrongPinFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wpLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wpButton1)
                    .addComponent(wpButton2))
                .addGap(24, 24, 24))
        );

        PinPanel.add(WrongPinFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 350, 210));

        pBankLabel.setFont(new java.awt.Font("Marcellus SC", 1, 36)); // NOI18N
        pBankLabel.setForeground(new java.awt.Color(255, 255, 255));
        pBankLabel.setText("UnprivateBank");
        PinPanel.add(pBankLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 277, -1));

        pEnterLabel.setBackground(new java.awt.Color(102, 102, 0));
        pEnterLabel.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        pEnterLabel.setForeground(new java.awt.Color(255, 255, 255));
        pEnterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconPin.png"))); // NOI18N
        pEnterLabel.setText("Enter PIN");
        PinPanel.add(pEnterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 65, 315, -1));

        pButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        pButton1.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        pButton1.setText("1");
        pButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButton1ActionPerformed(evt);
            }
        });
        PinPanel.add(pButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 183, 60, 39));

        pButton2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        pButton2.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        pButton2.setText("2");
        pButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButton2ActionPerformed(evt);
            }
        });
        PinPanel.add(pButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 183, 60, 39));

        pButton3.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        pButton3.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        pButton3.setText("3");
        pButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButton3ActionPerformed(evt);
            }
        });
        PinPanel.add(pButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 183, 60, 39));

        pButton4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        pButton4.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        pButton4.setText("4");
        pButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButton4ActionPerformed(evt);
            }
        });
        PinPanel.add(pButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 228, 60, 39));

        pButton5.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        pButton5.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        pButton5.setText("5");
        pButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButton5ActionPerformed(evt);
            }
        });
        PinPanel.add(pButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 228, 60, 39));

        pButton6.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        pButton6.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        pButton6.setText("6");
        pButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButton6ActionPerformed(evt);
            }
        });
        PinPanel.add(pButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 228, 60, 39));

        pButton7.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        pButton7.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        pButton7.setText("7");
        pButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButton7ActionPerformed(evt);
            }
        });
        PinPanel.add(pButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 274, 60, 39));

        pButton8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        pButton8.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        pButton8.setText("8");
        pButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButton8ActionPerformed(evt);
            }
        });
        PinPanel.add(pButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 274, 60, 39));

        pButton9.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        pButton9.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        pButton9.setText("9");
        pButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButton9ActionPerformed(evt);
            }
        });
        PinPanel.add(pButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 274, 60, 39));

        pButton0.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        pButton0.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        pButton0.setText("0");
        pButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButton0ActionPerformed(evt);
            }
        });
        PinPanel.add(pButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 319, 60, 39));

        pButtonDel.setBackground(new java.awt.Color(204, 0, 0));
        pButtonDel.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        pButtonDel.setText("X");
        pButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButtonDelActionPerformed(evt);
            }
        });
        PinPanel.add(pButtonDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 319, 60, 39));

        pButtonNext.setBackground(new java.awt.Color(51, 204, 0));
        pButtonNext.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        pButtonNext.setText("Next");
        pButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButtonNextActionPerformed(evt);
            }
        });
        PinPanel.add(pButtonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 319, 60, 39));

        pPasswordField.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        pPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        pPasswordField.setEchoChar('\u25cf');
        pPasswordField.setFocusAccelerator('\u25b2');
        pPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPasswordFieldActionPerformed(evt);
            }
        });
        PinPanel.add(pPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 127, 192, 46));

        getContentPane().add(PinPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 390));

        StartPanel.setBackground(new java.awt.Color(0, 100, 39));

        sBankLabel.setBackground(new java.awt.Color(0, 0, 0));
        sBankLabel.setFont(new java.awt.Font("Marcellus SC", 1, 36)); // NOI18N
        sBankLabel.setForeground(new java.awt.Color(255, 255, 255));
        sBankLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconPrivate.png"))); // NOI18N
        sBankLabel.setText("₴UnprivateBank");

        sLabel1.setBackground(new java.awt.Color(255, 255, 255));
        sLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        sLabel1.setForeground(new java.awt.Color(255, 255, 255));
        sLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconPhone.png"))); // NOI18N
        sLabel1.setText("   Top up account");
        sLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        sLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sLabel2.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        sLabel2.setForeground(new java.awt.Color(255, 255, 255));
        sLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconCard.png"))); // NOI18N
        sLabel2.setText("Replenish the card");
        sLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        sLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sLabel2MouseClicked(evt);
            }
        });

        java.util.Date date = new java.util.Date();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd.MM.yyyy");
        String dateString = sdf.format(date);
        sDatalabelPanel.setFont(new java.awt.Font("Marcellus SC", 1, 18)); // NOI18N
        sDatalabelPanel.setForeground(new java.awt.Color(255, 255, 255));
        sDatalabelPanel.setText(dateString);

        sLabel3.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        sLabel3.setForeground(new java.awt.Color(255, 255, 255));
        sLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconHelp.png"))); // NOI18N
        sLabel3.setText("Contact with us");
        sLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        sLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sSeparator.setForeground(new java.awt.Color(255, 255, 255));
        sSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        sSeparator.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        sInsertLabel.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        sInsertLabel.setForeground(new java.awt.Color(255, 255, 255));
        sInsertLabel.setText("Insert the card or fill a phone number");

        sPhoneLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconPhone.png"))); // NOI18N

        sPhoneField.setBackground(new java.awt.Color(0, 161, 33));
        sPhoneField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        sPhoneField.setForeground(new java.awt.Color(255, 255, 255));
        try {
            sPhoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)##-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        sPhoneField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sPhoneField.setText("(380)63-632-4190    ");
        sPhoneField.setFont(new java.awt.Font("Marcellus SC", 1, 14)); // NOI18N
        sPhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPhoneFieldActionPerformed(evt);
            }
        });

        sLabel4.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        sLabel4.setForeground(new java.awt.Color(255, 255, 255));
        sLabel4.setText("Sign In");
        sLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        sLabel5.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        sLabel5.setForeground(new java.awt.Color(255, 255, 255));
        sLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconCreate.png"))); // NOI18N
        sLabel5.setText("Create an account");
        sLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        sLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sLabel5MouseClicked(evt);
            }
        });

        sButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        sButton1.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        sButton1.setText("1");
        sButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButton1ActionPerformed(evt);
            }
        });

        sButton2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        sButton2.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        sButton2.setText("2");
        sButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButton2ActionPerformed(evt);
            }
        });

        sButton3.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        sButton3.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        sButton3.setText("3");
        sButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButton3ActionPerformed(evt);
            }
        });

        sButton4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        sButton4.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        sButton4.setText("4");
        sButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButton4ActionPerformed(evt);
            }
        });

        sButton5.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        sButton5.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        sButton5.setText("5");
        sButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButton5ActionPerformed(evt);
            }
        });

        sButton6.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        sButton6.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        sButton6.setText("6");
        sButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButton6ActionPerformed(evt);
            }
        });

        sButton7.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        sButton7.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        sButton7.setText("7");
        sButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButton7ActionPerformed(evt);
            }
        });

        sButton8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        sButton8.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        sButton8.setText("8");
        sButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButton8ActionPerformed(evt);
            }
        });

        sButton9.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        sButton9.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        sButton9.setText("9");
        sButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButton9ActionPerformed(evt);
            }
        });

        sButton0.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        sButton0.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        sButton0.setText("0");
        sButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButton0ActionPerformed(evt);
            }
        });

        sButtonDel.setBackground(new java.awt.Color(204, 0, 0));
        sButtonDel.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        sButtonDel.setText("X");
        sButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButtonDelActionPerformed(evt);
            }
        });

        sButtonNext.setBackground(new java.awt.Color(51, 204, 0));
        sButtonNext.setFont(new java.awt.Font("Marcellus SC", 1, 24)); // NOI18N
        sButtonNext.setText("Next");
        sButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButtonNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StartPanelLayout = new javax.swing.GroupLayout(StartPanel);
        StartPanel.setLayout(StartPanelLayout);
        StartPanelLayout.setHorizontalGroup(
            StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sBankLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sDatalabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(sSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StartPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sInsertLabel)
                            .addGroup(StartPanelLayout.createSequentialGroup()
                                .addComponent(sPhoneLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(StartPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StartPanelLayout.createSequentialGroup()
                                .addComponent(sButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StartPanelLayout.createSequentialGroup()
                                .addComponent(sButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StartPanelLayout.createSequentialGroup()
                                .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(StartPanelLayout.createSequentialGroup()
                                        .addComponent(sButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(StartPanelLayout.createSequentialGroup()
                                        .addComponent(sButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(StartPanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(sLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        StartPanelLayout.setVerticalGroup(
            StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StartPanelLayout.createSequentialGroup()
                        .addComponent(sBankLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sLabel1)
                        .addGap(7, 7, 7)
                        .addComponent(sLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sLabel5)
                        .addGap(31, 31, 31)
                        .addComponent(sDatalabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(StartPanelLayout.createSequentialGroup()
                        .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(StartPanelLayout.createSequentialGroup()
                                .addComponent(sLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sPhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(StartPanelLayout.createSequentialGroup()
                                        .addComponent(sInsertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25))))
        );

        getContentPane().add(StartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 390));

        PanelUserMenu.setBackground(new java.awt.Color(0, 102, 0));
        PanelUserMenu.setVisible(false);

        PanelMenuLogo.setFont(new java.awt.Font("Marcellus SC", 1, 36)); // NOI18N
        PanelMenuLogo.setForeground(new java.awt.Color(255, 255, 255));
        PanelMenuLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconPrivate.png"))); // NOI18N
        PanelMenuLogo.setText("UnprivateBank");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N

        PanelMenuTitle.setFont(new java.awt.Font("Marcellus SC", 1, 36)); // NOI18N
        PanelMenuTitle.setForeground(new java.awt.Color(255, 255, 255));
        PanelMenuTitle.setText("Main menu");

        PanelMenuTopUp.setBackground(new java.awt.Color(255, 255, 255));
        PanelMenuTopUp.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        PanelMenuTopUp.setForeground(new java.awt.Color(255, 255, 255));
        PanelMenuTopUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconPhone.png"))); // NOI18N
        PanelMenuTopUp.setText("   Top up account");
        PanelMenuTopUp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        PanelMenuTopUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PanelMenuReplenish.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        PanelMenuReplenish.setForeground(new java.awt.Color(255, 255, 255));
        PanelMenuReplenish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconCard.png"))); // NOI18N
        PanelMenuReplenish.setText("Replenish the card");
        PanelMenuReplenish.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        PanelMenuReplenish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelMenuReplenish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMenuReplenishMouseClicked(evt);
            }
        });

        PanelMenuContacts.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        PanelMenuContacts.setForeground(new java.awt.Color(255, 255, 255));
        PanelMenuContacts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconHelp.png"))); // NOI18N
        PanelMenuContacts.setText("Contact with us");
        PanelMenuContacts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        PanelMenuContacts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PanelMenuBalance.setBackground(new java.awt.Color(255, 255, 255));
        PanelMenuBalance.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        PanelMenuBalance.setForeground(new java.awt.Color(255, 255, 255));
        PanelMenuBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconBalance.png"))); // NOI18N
        PanelMenuBalance.setText("   Check balance");
        PanelMenuBalance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        PanelMenuBalance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelMenuBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMenuBalanceMouseClicked(evt);
            }
        });

        PanelMenuTransfer.setBackground(new java.awt.Color(255, 255, 255));
        PanelMenuTransfer.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        PanelMenuTransfer.setForeground(new java.awt.Color(255, 255, 255));
        PanelMenuTransfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconTransfer.png"))); // NOI18N
        PanelMenuTransfer.setText("   Make transfer");
        PanelMenuTransfer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        PanelMenuTransfer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PanelMenuExit.setBackground(new java.awt.Color(255, 255, 255));
        PanelMenuExit.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        PanelMenuExit.setForeground(new java.awt.Color(255, 255, 255));
        PanelMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconExit.png"))); // NOI18N
        PanelMenuExit.setText("          Exit");
        PanelMenuExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        PanelMenuExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMenuExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelUserMenuLayout = new javax.swing.GroupLayout(PanelUserMenu);
        PanelUserMenu.setLayout(PanelUserMenuLayout);
        PanelUserMenuLayout.setHorizontalGroup(
            PanelUserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUserMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelUserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUserMenuLayout.createSequentialGroup()
                        .addGroup(PanelUserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelUserMenuLayout.createSequentialGroup()
                                .addComponent(PanelMenuContacts, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PanelMenuExit, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelUserMenuLayout.createSequentialGroup()
                                .addComponent(PanelMenuReplenish, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(240, 240, 240)
                                .addComponent(PanelMenuTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(PanelUserMenuLayout.createSequentialGroup()
                        .addComponent(PanelMenuTopUp, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelMenuBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(PanelUserMenuLayout.createSequentialGroup()
                        .addComponent(PanelMenuLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelMenuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        PanelUserMenuLayout.setVerticalGroup(
            PanelUserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUserMenuLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(PanelUserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelMenuTitle)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelMenuLogo))
                .addGap(29, 29, 29)
                .addGroup(PanelUserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PanelMenuTopUp)
                    .addComponent(PanelMenuBalance))
                .addGap(7, 7, 7)
                .addGroup(PanelUserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PanelMenuReplenish)
                    .addComponent(PanelMenuTransfer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelUserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PanelMenuContacts)
                    .addComponent(PanelMenuExit))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        getContentPane().add(PanelUserMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sPhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPhoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sPhoneFieldActionPerformed

    private void pButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButton2ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToPasswordField(pPasswordField, 2);
    }//GEN-LAST:event_pButton2ActionPerformed

    private void pButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButton1ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToPasswordField(pPasswordField, 1);
    }//GEN-LAST:event_pButton1ActionPerformed

    private void pButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButton3ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToPasswordField(pPasswordField, 3);
    }//GEN-LAST:event_pButton3ActionPerformed

    private void pButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButton4ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToPasswordField(pPasswordField, 4);
    }//GEN-LAST:event_pButton4ActionPerformed

    private void pButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButton5ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToPasswordField(pPasswordField, 5);
    }//GEN-LAST:event_pButton5ActionPerformed

    private void pButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButton6ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToPasswordField(pPasswordField, 6);
    }//GEN-LAST:event_pButton6ActionPerformed

    private void pButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButton8ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToPasswordField(pPasswordField, 8);
    }//GEN-LAST:event_pButton8ActionPerformed

    private void pButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButton7ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToPasswordField(pPasswordField, 7);
    }//GEN-LAST:event_pButton7ActionPerformed

    private void pButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButton0ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToPasswordField(pPasswordField, 0);
    }//GEN-LAST:event_pButton0ActionPerformed

    private void pButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButton9ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToPasswordField(pPasswordField, 9);
    }//GEN-LAST:event_pButton9ActionPerformed

    private void pButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButtonNextActionPerformed
        // TODO add your handling code here:
        String stringPassword = new String(pPasswordField.getPassword());
        if (stringPassword.length() == 4) {
            int inputPassword = Integer.parseInt(new String(pPasswordField.getPassword()));
            if (inputPassword == currentUser.getPin()) {
                PinPanel.setVisible(false);
                PanelUserMenu.setVisible(true);
            } else {
                WrongPinFrame.setVisible(true);
                System.out.println("ERROR: wrong PIN");
            }
        }

    }//GEN-LAST:event_pButtonNextActionPerformed

    private void pButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButtonDelActionPerformed
        // TODO add your handling code here:
        TB.DeleteFromPasswordField(pPasswordField);
    }//GEN-LAST:event_pButtonDelActionPerformed

    private void sButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButton2ActionPerformed
        TB.AddDigitToFormattedTextField(sPhoneField, 2);
    }//GEN-LAST:event_sButton2ActionPerformed

    private void sButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButton1ActionPerformed
        TB.AddDigitToFormattedTextField(sPhoneField, 1);
//        String phoneInputRes = jFormattedTextField2.getValue().toString();
//        
//        if(phoneInputRes.length() == 0) {
//            jFormattedTextField2.setValue("(" + 1);
//        } else if(phoneInputRes.length() == 4) {
//            jFormattedTextField2.setValue(phoneInputRes + ")1");
//        } else if(phoneInputRes.length() == 7) {
//            jFormattedTextField2.setValue(phoneInputRes + "-1");
//        } else if(phoneInputRes.length() == 11) {
//            jFormattedTextField2.setValue(phoneInputRes + "-1");
//        } else if(phoneInputRes.length() >= 16) {
//            return;
//        }
//        else {
//            jFormattedTextField2.setValue(phoneInputRes + "1");
//            System.out.println("Len: " + phoneInputRes.length());
//        }
//        
//        
//        System.out.println("RES: " + jFormattedTextField2.getValue().toString());
    }//GEN-LAST:event_sButton1ActionPerformed

    private void sButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButton3ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToFormattedTextField(sPhoneField, 3);
    }//GEN-LAST:event_sButton3ActionPerformed

    private void sButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButton4ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToFormattedTextField(sPhoneField, 4);
    }//GEN-LAST:event_sButton4ActionPerformed

    private void sButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButton5ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToFormattedTextField(sPhoneField, 5);
    }//GEN-LAST:event_sButton5ActionPerformed

    private void sButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButton6ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToFormattedTextField(sPhoneField, 6);
    }//GEN-LAST:event_sButton6ActionPerformed

    private void sButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButton7ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToFormattedTextField(sPhoneField, 7);
    }//GEN-LAST:event_sButton7ActionPerformed

    private void sButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButton8ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToFormattedTextField(sPhoneField, 8);
//        System.out.println(8);
    }//GEN-LAST:event_sButton8ActionPerformed

    private void sButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButton9ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToFormattedTextField(sPhoneField, 9);
    }//GEN-LAST:event_sButton9ActionPerformed

    private void sButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButton0ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToFormattedTextField(sPhoneField, 0);
    }//GEN-LAST:event_sButton0ActionPerformed

    private void sButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButtonDelActionPerformed
        // TODO add your handling code here:
        TB.DeleteFromFormattedTextField(sPhoneField);
    }//GEN-LAST:event_sButtonDelActionPerformed


    private void sButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButtonNextActionPerformed
        // TODO add your handling code here:
        String phoneInputRes = sPhoneField.getValue().toString();
        List<User> users = DataBaseObject.SelectAll();
        DataBaseObject.writeDataBase();
        User resultUser = null;
        for (int i = 0; i < users.size(); i++) {
            if (users.get(i).getTelephone().equals(phoneInputRes)) {
                resultUser = users.get(i);
                break;
            }
        }
        if (resultUser != null) {
            // NEXT -> Check PIN
            currentUser = resultUser;
            System.out.println("Succes -> ID: " + currentUser.getId());
            StartPanel.setVisible(false);
            PinPanel.setVisible(true);

        } else {
            System.out.println("ERROR: no such number!");
        }
    }//GEN-LAST:event_sButtonNextActionPerformed

    private void sLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sLabel5MouseClicked
        // TODO add your handling code here:
//      ConsoleApp CA = new ConsoleApp();
        User client = new User();
        client.Card_number();
        client.Pin();
        client.User_name("Kolia Strelkov");
        client.Email("kjsdjs");
        client.Telephone("9873742583289");

        DataBaseObject.Insert(client);
    }//GEN-LAST:event_sLabel5MouseClicked

    private void pPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pPasswordFieldActionPerformed

    private void wpButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wpButton1ActionPerformed
        // TODO add your handling code here:
        WrongPinFrame.setVisible(false);
        pPasswordField.setText("");
        PinPanel.setVisible(false);
        StartPanel.setVisible(true);
        currentUser = null;
    }//GEN-LAST:event_wpButton1ActionPerformed

    private void wpButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wpButton2ActionPerformed
        // TODO add your handling code here:
         WrongPinFrame.setVisible(false);
        pPasswordField.setText("");
    }//GEN-LAST:event_wpButton2ActionPerformed

    private void PanelMenuBalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuBalanceMouseClicked
        // TODO add your handling code here:
        System.out.println("Hello, " + currentUser.getUser_name() + " | Your balance: " + currentUser.getBalance());
    }//GEN-LAST:event_PanelMenuBalanceMouseClicked

    private void PanelMenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuExitMouseClicked
        // TODO add your handling code here:
        pPasswordField.setText("");
        PanelUserMenu.setVisible(false);
        StartPanel.setVisible(true);
        currentUser = null;
    }//GEN-LAST:event_PanelMenuExitMouseClicked

    private void PanelMenuReplenishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuReplenishMouseClicked
        // TODO add your handling code here:
        System.out.println("Mouse Clicked!");
        System.out.println("Another changes!");
    }//GEN-LAST:event_PanelMenuReplenishMouseClicked

    private void sLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sLabel2MouseClicked
        // TODO add your handling code here:
        StartPanel.setVisible(false);
        CardPanel.setVisible(true);
        
    }//GEN-LAST:event_sLabel2MouseClicked

    private void CardFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardFieldActionPerformed

    private void cButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButton1ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToCardField(CardField, 1);
    }//GEN-LAST:event_cButton1ActionPerformed

    private void cButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButton2ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToCardField(CardField, 2);
    }//GEN-LAST:event_cButton2ActionPerformed

    private void cButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButton3ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToCardField(CardField, 3);
    }//GEN-LAST:event_cButton3ActionPerformed

    private void cButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButton4ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToCardField(CardField, 4);
    }//GEN-LAST:event_cButton4ActionPerformed

    private void cButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButton5ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToCardField(CardField, 5);
    }//GEN-LAST:event_cButton5ActionPerformed

    private void cButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButton6ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToCardField(CardField, 6);
    }//GEN-LAST:event_cButton6ActionPerformed

    private void cButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButton7ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToCardField(CardField, 7);
    }//GEN-LAST:event_cButton7ActionPerformed

    private void cButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButton8ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToCardField(CardField, 8);
    }//GEN-LAST:event_cButton8ActionPerformed

    private void cButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButton9ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToCardField(CardField, 9);
    }//GEN-LAST:event_cButton9ActionPerformed

    private void cButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonDelActionPerformed
        // TODO add your handling code here:
        TB.DeleteFromFormattedTextField(CardField);
    }//GEN-LAST:event_cButtonDelActionPerformed

    private void cButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButton0ActionPerformed
        // TODO add your handling code here:
        TB.AddDigitToCardField(CardField, 0);
    }//GEN-LAST:event_cButton0ActionPerformed

    private void cButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonNextActionPerformed
        // TODO add your handling code here:
        String cardInputRes = CardField.getValue().toString();
        List<User> users = DataBaseObject.SelectAll();
        User resultUser = null;
        for (int i = 0; i < users.size(); i++) {
            if (users.get(i).getCard_Number().equals(cardInputRes)) {
                resultUser = users.get(i);
                break;
            }
        }
        if (resultUser != null) {
            // NEXT -> Check PIN
            currentUser = resultUser;
            System.out.println("Succes -> ID: " + currentUser.getId());
            CardPanel.setVisible(false);
            PinPanel.setVisible(true);

        } else {
            System.out.println("ERROR: no such number!");
            System.out.println(cardInputRes);
        }
    }//GEN-LAST:event_cButtonNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_terminal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CardField;
    private javax.swing.JLabel CardLabel;
    private javax.swing.JPanel CardPanel;
    private javax.swing.JLabel InsertLabel;
    private javax.swing.JLabel PanelMenuBalance;
    private javax.swing.JLabel PanelMenuContacts;
    private javax.swing.JLabel PanelMenuExit;
    private javax.swing.JLabel PanelMenuLogo;
    private javax.swing.JLabel PanelMenuReplenish;
    private javax.swing.JLabel PanelMenuTitle;
    private javax.swing.JLabel PanelMenuTopUp;
    private javax.swing.JLabel PanelMenuTransfer;
    private javax.swing.JPanel PanelUserMenu;
    private javax.swing.JPanel PinPanel;
    private javax.swing.JLabel SignInLabel;
    private javax.swing.JPanel StartPanel;
    private javax.swing.JInternalFrame WrongPinFrame;
    private javax.swing.JLabel cBankLabel;
    private javax.swing.JButton cButton0;
    private javax.swing.JButton cButton1;
    private javax.swing.JButton cButton2;
    private javax.swing.JButton cButton3;
    private javax.swing.JButton cButton4;
    private javax.swing.JButton cButton5;
    private javax.swing.JButton cButton6;
    private javax.swing.JButton cButton7;
    private javax.swing.JButton cButton8;
    private javax.swing.JButton cButton9;
    private javax.swing.JButton cButtonDel;
    private javax.swing.JButton cButtonNext;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel pBankLabel;
    private javax.swing.JButton pButton0;
    private javax.swing.JButton pButton1;
    private javax.swing.JButton pButton2;
    private javax.swing.JButton pButton3;
    private javax.swing.JButton pButton4;
    private javax.swing.JButton pButton5;
    private javax.swing.JButton pButton6;
    private javax.swing.JButton pButton7;
    private javax.swing.JButton pButton8;
    private javax.swing.JButton pButton9;
    private javax.swing.JButton pButtonDel;
    private javax.swing.JButton pButtonNext;
    private javax.swing.JLabel pEnterLabel;
    private javax.swing.JPasswordField pPasswordField;
    private javax.swing.JLabel sBankLabel;
    private javax.swing.JButton sButton0;
    private javax.swing.JButton sButton1;
    private javax.swing.JButton sButton2;
    private javax.swing.JButton sButton3;
    private javax.swing.JButton sButton4;
    private javax.swing.JButton sButton5;
    private javax.swing.JButton sButton6;
    private javax.swing.JButton sButton7;
    private javax.swing.JButton sButton8;
    private javax.swing.JButton sButton9;
    private javax.swing.JButton sButtonDel;
    private javax.swing.JButton sButtonNext;
    private javax.swing.JLabel sDatalabelPanel;
    private javax.swing.JLabel sInsertLabel;
    private javax.swing.JLabel sLabel1;
    private javax.swing.JLabel sLabel2;
    private javax.swing.JLabel sLabel3;
    private javax.swing.JLabel sLabel4;
    private javax.swing.JLabel sLabel5;
    private javax.swing.JFormattedTextField sPhoneField;
    private javax.swing.JLabel sPhoneLabel;
    private javax.swing.JSeparator sSeparator;
    private javax.swing.JButton wpButton1;
    private javax.swing.JButton wpButton2;
    private javax.swing.JLabel wpLabel1;
    private javax.swing.JLabel wpLabel2;
    // End of variables declaration//GEN-END:variables
}
